// src/app/layout.tsx

import { NextUIProvider } from "@nextui-org/react";
import { Inter } from "next/font/google";
import "../../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href={inter.stylesheet} />
      </head>
      <body className={inter.className}>
        {/* Wrap content with NextUIProvider */}
        {/* <NextUIProvider> */}
          {children}
        {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
